return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    plugins = { spelling = true },
  },
  config = function(_, opts)
    local wk = require("which-key")
    wk.setup(opts)
    local keymaps = {
      mode = { "n", "v" },
      ["g"] = { name = "+goto" },
      ["gs"] = { name = "+surround" },
      ["z"] = { name = "+fold" },
      ["]"] = { name = "+next" },
      ["["] = { name = "+prev" },
      -- ["<leader>gh"] = { name = "+hunks" },
      ["<leader>g"] = { name = "+Git" },
      ["<leader>gh"] = { name = "+Github" },
      ["<leader>ghc"] = { name = "+Commits" },
      ["<leader>ghcc"] = { "<cmd>GHCloseCommit<cr>", "Close" },
      ["<leader>ghce"] = { "<cmd>GHExpandCommit<cr>", "Expand" },
      ["<leader>ghco"] = { "<cmd>GHOpenToCommit<cr>", "Open To" },
      ["<leader>ghcp"] = { "<cmd>GHPopOutCommit<cr>", "Pop Out" },
      ["<leader>ghcz"] = { "<cmd>GHCollapseCommit<cr>", "Collapse" },
      ["<leader>ghi"] = { name = "+Issues" },
      ["<leader>ghip"] = { "<cmd>GHPreviewIssue<cr>", "Preview" },
      ["<leader>ghl"] = { name = "+Litee" },
      ["<leader>ghlt"] = { "<cmd>LTPanel<cr>", "Toggle Panel" },
      ["<leader>ghr"] = { name = "+Review" },
      ["<leader>ghrb"] = { "<cmd>GHStartReview<cr>", "Begin" },
      ["<leader>ghrc"] = { "<cmd>GHCloseReview<cr>", "Close" },
      ["<leader>ghrd"] = { "<cmd>GHDeleteReview<cr>", "Delete" },
      ["<leader>ghre"] = { "<cmd>GHExpandReview<cr>", "Expand" },
      ["<leader>ghrs"] = { "<cmd>GHSubmitReview<cr>", "Submit" },
      ["<leader>ghrz"] = { "<cmd>GHCollapseReview<cr>", "Collapse" },
      ["<leader>ghp"] = { name = "+Pull Request" },
      ["<leader>ghpc"] = { "<cmd>GHClosePR<cr>", "Close" },
      ["<leader>ghpd"] = { "<cmd>GHPRDetails<cr>", "Details" },
      ["<leader>ghpe"] = { "<cmd>GHExpandPR<cr>", "Expand" },
      ["<leader>ghpo"] = { "<cmd>GHOpenPR<cr>", "Open" },
      ["<leader>ghpp"] = { "<cmd>GHPopOutPR<cr>", "PopOut" },
      ["<leader>ghpr"] = { "<cmd>GHRefreshPR<cr>", "Refresh" },
      ["<leader>ghpt"] = { "<cmd>GHOpenToPR<cr>", "Open To" },
      ["<leader>ghpz"] = { "<cmd>GHCollapsePR<cr>", "Collapse" },
      ["<leader>ght"] = { name = "+Threads" },
      ["<leader>ghtc"] = { "<cmd>GHCreateThread<cr>", "Create" },
      ["<leader>ghtn"] = { "<cmd>GHNextThread<cr>", "Next" },
      ["<leader>ghtt"] = { "<cmd>GHToggleThread<cr>", "Toggle" },
      ["<leader><tab>"] = { name = "+tabs" },
      ["<leader><leader>"] = { name = "+misc" },
      ["<leader>b"] = { name = "+buffer" },
      ["<leader>c"] = { name = "+code" },
      ["<leader>d"] = { name = "+DAP" },
      ["<leader>f"] = { name = "+file/find" },
      ["<leader>h"] = { name = "+harpoon" },
      ["<leader>j"] = { name = "+jupyter" },
      ["<leader>q"] = { name = "+quit/session" },
      ["<leader>l"] = { name = "+LSP" },
      ["<leader>la"] = { name = "+LSP Actions" },
      ["<leader>lc"] = { name = "+LSP Codelens" },
      ["<leader>ll"] = { name = "+LSP LogFuncs" },
      ["<leader>llo"] = { name = "+LSP LogFuncs" },
      ["<leader>m"] = { name = "+macro" },
      ["<leader>p"] = { name = "+plugins" },
      ["<leader>pc"] = { name = "+choco" },
      ["<leader>pcu"] = { name = "+choco upgrade" },
      ["<leader>s"] = { name = "+search" },
      ["<leader>sq"] = { name = "+Dbee" },
      ["<leader>t"] = { name = "+term/testing" },
      ["<leader>u"] = { name = "+ui" },
      ["<leader>w"] = { "<Cmd>w<CR>", "Save Buffer" },
      ["<leader>x"] = { name = "+diagnostics/quickfix" },
    }

    -- if require("lazy.Util").has("noice.nvim") then
    keymaps["<leader>sn"] = { name = "+noice" }
    -- end
    wk.register(keymaps)
  end,
}
